"""initial

Revision ID: 2ebff43c7caa
Revises:
Create Date: 2026-08-16 15:39:19.423362

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2ebff43c7caa"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "players",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("nickname", sa.String(length=32), nullable=False),
        sa.Column("money", sa.Integer(), nullable=False),
        sa.Column("rating", sa.Float(), nullable=False),
        sa.Column("tutorial_done", sa.Boolean(), nullable=False),
        sa.Column("day", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("nickname"),
    )
    op.create_table(
        "game_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("player_id", sa.UUID(), nullable=False),
        sa.Column("event_type", sa.String(length=32), nullable=False),
        sa.Column("description", sa.String(length=256), nullable=False),
        sa.Column("money_delta", sa.Integer(), nullable=False),
        sa.Column("rating_delta", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["players.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "orders",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("player_id", sa.UUID(), nullable=False),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.Column("reward", sa.Integer(), nullable=False),
        sa.Column("urgency", sa.Integer(), nullable=False),
        sa.Column("risk", sa.Float(), nullable=False),
        sa.Column("from_x", sa.Float(), nullable=False),
        sa.Column("from_y", sa.Float(), nullable=False),
        sa.Column("to_x", sa.Float(), nullable=False),
        sa.Column("to_y", sa.Float(), nullable=False),
        sa.Column("zone", sa.String(length=16), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PENDING", "IN_PROGRESS", "DELIVERED", "FAILED", name="orderstatus"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["players.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "rovers",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("player_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=32), nullable=False),
        sa.Column("battery", sa.Float(), nullable=False),
        sa.Column("max_load", sa.Float(), nullable=False),
        sa.Column("current_load", sa.Float(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("IDLE", "DELIVERING", "STUCK", "CHARGING", name="roverstatus"),
            nullable=False,
        ),
        sa.Column("pos_x", sa.Float(), nullable=False),
        sa.Column("pos_y", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["players.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "deliveries",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("rover_id", sa.UUID(), nullable=False),
        sa.Column("order_id", sa.UUID(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("eta", sa.DateTime(), nullable=False),
        sa.Column("success", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
        ),
        sa.ForeignKeyConstraint(
            ["rover_id"],
            ["rovers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("deliveries")
    op.drop_table("rovers")
    op.drop_table("orders")
    op.drop_table("game_events")
    op.drop_table("players")
    # ### end Alembic commands ###
